using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Student
{
    class Student
    {
        string firstName;
        string lastName;
        public string phoneNum;
        public int age;
        public int classGrade;
        string[] no = { "a","b","c"};
        string[] mail = { "@mail.ru", "@gmail.com", "@box.ru","@hotmail.com","@yandex.ru" };
        int mathPoint = 90;
        int languagePoint =80;
        int physicPoint =87;
        int chemistryPoint =65;
        int biologyPoint=89;
        public string Email()
        {
            Random rand = new Random();
            int index = rand.Next(mail.Length);
            string email = firstName+lastName+mail[index];
            return email;
        }
        public string ClassNo()
        {
            Random rand = new Random();
            int index = rand.Next(no.Length);
            string classNo = classGrade + no[index];
            return classNo;
        }
        public double Gpa()
        {
            double sum = mathPoint+languagePoint+physicPoint+chemistryPoint+biologyPoint;
            double count = 5;
            double gpa = sum / count;
            return gpa; 
        }
        public string Name() { return firstName+" "+lastName; }
        public Student (string firstName,string lastName,int age,int classGrade,string phoneNumber)
        {
            this.firstName = firstName; 
            this.lastName = lastName;
            this.age = age;
            this.classGrade = classGrade;
            this.phoneNum = phoneNumber;
        }
    }

    internal class Program
    {
        static void Main(string[] args)
        {
            string fistname, lastname, phonenumber;
            int age, classgrade;
            Entering(out fistname, out lastname, out age, out classgrade, out phonenumber);
            Console.Clear();
            Console.WriteLine("your class number and email generated by our program");
            Student student1 = new Student(fistname, lastname, age, classgrade, phonenumber);
            Console.WriteLine($"student's name:{ student1.Name()}\n" +
                              $"student's age:{student1.age}\n" +
                              $"student's grade:{student1.classGrade}\n" +
                              $"student's phone number:{student1.phoneNum}\n");
            Console.WriteLine($"student's email: {student1.Email()}\nstudent Gpa: {student1.Gpa()}\nstudent classno: {student1.ClassNo()}");
            Console.ReadLine();

        }

        private static void Entering(out string fistname, out string lastname, out int age, out int classgrade, out string phonenumber)
        {
            Console.WriteLine("Enter your fist name:");
            fistname = Console.ReadLine();
            Console.WriteLine("Enter your last name:");
            lastname = Console.ReadLine();
            Console.WriteLine("Enter your age:");
            age = int.Parse(Console.ReadLine());
            Console.WriteLine("Enter your class grade:");
            classgrade = int.Parse(Console.ReadLine());
            Console.WriteLine("Enter your number:");
            phonenumber = Console.ReadLine();
        }
    }
}